recipes:
    global:
        - applications::mysql
    mac_os_x:
        - rvm::user
        - applications::sublime_text_3
        - osxdefaults::set_terminal_profile
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
attributes:
    mysql_root_password: "password"
    homebrewalt:
        apps:
            - git
            - git-extras
            - wget
        cask_apps:
            - sequel-pro
    rvm:
        user_installs:
            user: bjedrocha
            rubies:
                - 2.0.0
